---
spring:
  profiles:
    active: local
  first:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/pntbiz_beacon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
      type : javax.sql.DataSource
      maxActive: 50
      maxIdle: 0
      maxWait: -1
      validationQuery: SELECT 1
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 1800000
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: false